<div style='text-align: center;'>

# Reproducible randomness via seeding 

</div>

In [1]:
# importing needed libraries
import numpy as np
import torch

In [4]:
# generating couple random numbers
np.random.randn(5)

array([ 2.171257  ,  1.15231025, -1.81881234, -0.13804934,  0.53983961])

In [23]:
# repeat after fixing the seed (old method, still commonly used)
# every re-run of this code will yield the same values
np.random.seed(18)
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.07942844  2.19020236 -0.13489215  0.16051798  0.44269784]
[ 0.62339144  1.00890349  0.39424879 -0.3363867  -0.64590646]


<div style='text-align: center'>

# New, better seed mechanism in numpy

</div>

In [27]:
randomSeed1 = np.random.RandomState(18)
randomSeed2 = np.random.RandomState(3305415)

print(randomSeed1.randn(5)) # same sequence as above cell
print(randomSeed2.randn(5)) # different sequence than above but same each time
print(randomSeed1.randn(5)) 
print(randomSeed2.randn(5)) 
print(np.random.randn(5))   # different every time

[ 0.07942844  2.19020236 -0.13489215  0.16051798  0.44269784]
[-1.12164477  1.07130533  0.23517718 -0.01281058  0.70088777]
[ 0.62339144  1.00890349  0.39424879 -0.3363867  -0.64590646]
[-1.22440431 -0.40411698  0.28669081  0.97256366  0.623674  ]
[ 0.60136507 -0.56452682 -1.16795166 -1.02200224  0.88351955]


<div style='text-align: center'>

# Seeds in pytorch

</div>

In [37]:
torch.randn(5) # random each time

tensor([ 0.1534, -2.6631, -1.4311, -0.5483,  0.3232])

In [35]:
torch.manual_seed(17) # only local to torch, doesn't scope to numpy
print(torch.randn(5)) # doesn't change after first run

print(np.random.randn(5)) # different each time

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 1.13870114  0.67708514  0.30613517 -0.01527223  2.06798861]
