In [1]:
# import needed libraries 
import numpy as np
import torch 
import torch.nn as nn

<center>

# Min/Max using numpy

<center>

In [3]:
# creating a vector
vector = np.array([2,44,5,-4])

# find max min and output
minValue = np.min(vector)
maxValue = np.max(vector)
print("Min, Max: %g,%g" %(minValue, maxValue))

# find max min indices and output
minIndex = np.argmin(vector)
maxIndex = np.argmax(vector)
print("Min, Max indices: %g,%g" %(minIndex, maxIndex))

Min, Max: -4,44
Min, Max indices: 3,1


In [9]:
# min maxing with matrix
matrix = np.array([ [1,2,11],
                    [21,9,6] ])
print(matrix)

minWholeMatrx = np.min(matrix)
minEachColumn = np.min(matrix,axis=0)
minEachRow = np.min(matrix,axis=1)

print("\n",minWholeMatrx,"\n",minEachColumn,"\n",minEachRow)

[[ 1  2 11]
 [21  9  6]]

 1 
 [1 2 6] 
 [1 6]


In [10]:
# get the min index
print(matrix)

minIDXWholeMatrx = np.argmin(matrix)
minIDXEachColumn = np.argmin(matrix,axis=0)
minIDXEachRow = np.argmin(matrix,axis=1)

print("\n",minIDXWholeMatrx,"\n",minIDXEachColumn,"\n",minIDXEachRow)

[[ 1  2 11]
 [21  9  6]]

 0 
 [0 0 1] 
 [0 2]


<center>

# Now with pytorch

<center>

In [17]:
# creating tensor
tensor = torch.tensor([2,44,5,-4])

# find max min and output
minValue = torch.min(tensor)
maxValue = torch.max(tensor)
print("Min, Max: %g,%g" %(minValue, maxValue))

# find max min indices and output
minIndex = torch.argmin(tensor)
maxIndex = torch.argmax(tensor)
print("Min, Max indices: %g,%g" %(minIndex, maxIndex))

Min, Max: -4,44
Min, Max indices: 3,1


In [24]:
# multi-dimensional tensor
tensor = torch.tensor([ [1,2,11],
                        [21,9,6] ])
print(tensor)

minWholeMatrx = torch.min(tensor)
minEachColumn = torch.min(tensor,axis=0)
minEachRow = torch.min(tensor,axis=1)

print("\n",minWholeMatrx)
print("\n",minEachColumn)
print("\n",minEachRow)

tensor([[ 1,  2, 11],
        [21,  9,  6]])

 tensor(1)

 torch.return_types.min(
values=tensor([1, 2, 6]),
indices=tensor([0, 0, 1]))

 torch.return_types.min(
values=tensor([1, 6]),
indices=tensor([0, 2]))
