In [45]:
# import needed libraries 
import numpy as np
import torch

# Matrix Multiplication using Numpy

In [46]:
# creating random matrices 
# np.random.randn(RowNum, ColumnNum) will return a matrix filled with random floats in the dimension you input
matrixA = np.random.randn(2,5) # returns a matrix with 2 rows and 5 columns
matrixB = np.random.randn(5,4) # returns a matrix with 5 rows and 4 columns
matrixC = np.random.randn(2,4) # returns a matrix with 2 rows and 4 columns

print("\nA\n",matrixA)
print("\nB\n", matrixB)
print("\nC\n",matrixC)


A
 [[ 0.84284571 -0.53905509 -1.1219696   0.42076854 -0.67904038]
 [ 0.92947648 -0.51931632  2.72303544  0.53004809 -1.62294233]]

B
 [[ 0.600661    2.16249643 -1.7089381   0.50682648]
 [-0.50358287  0.05140932  0.67741377  2.38504788]
 [ 0.03387629  1.30273256 -0.44944732 -1.15760776]
 [ 0.90305963  0.64692371  0.20057797 -0.45794387]
 [-1.5014698  -1.24886323  0.2089804   1.42704882]]

C
 [[ 0.50419749 -0.26659585  1.49009378 -1.3993087 ]
 [ 1.34873173  0.66336382 -1.94922327 -1.93325859]]


In [47]:
# use @ sign for matrix multiplication shortcut with numpy
# np.matmul(A,B) == A@B

print("A x B")
print(np.round(matrixA@matrixB, 2)) # calculates matrix multiplication and rounds to 2 decimals
print("\nA x B other way")
print(np.round(np.matmul(matrixA, matrixB),2))

A x B
[[ 2.14  1.45 -1.36 -0.72]
 [ 3.83  7.9  -3.4  -6.48]]

A x B other way
[[ 2.14  1.45 -1.36 -0.72]
 [ 3.83  7.9  -3.4  -6.48]]


In [48]:
# incompatible dimensions example
# print("B x C")
# print(np.round(matrixB@matrixC, 2)) # dimension misalignment

# using transpose to get aligned dimensions
print("B x C^T")
print(np.round(matrixB@matrixC.T, 2))

B x C^T
[[-3.53  4.6 ]
 [-2.6  -6.58]
 [ 0.62  4.02]
 [ 1.22  2.14]
 [-2.11 -6.02]]


# Matrix Multiplication using Pytorch

In [49]:
# creating random tensors 
# torch.randn(RowNum, ColumnNum) will return a tensor filled with random floats in the dimension you input
tensorA = torch.randn(2,5) # returns a tensor with 2 rows and 5 columns
tensorB = torch.randn(5,4) # returns a tensor with 5 rows and 4 columns
tensorC = torch.randn(2,4) # returns a tensor with 2 rows and 4 columns


print("\nA\n",tensorA)
print("\nB\n", tensorB)
print("\nC\n",tensorC)


A
 tensor([[ 0.4840,  0.5935, -0.3984,  0.3251, -1.5931],
        [ 0.3392,  1.9246,  1.2867,  0.9914,  1.2558]])

B
 tensor([[-1.3598,  0.6401,  0.0982,  0.2894],
        [-1.0565, -0.1219,  0.8383, -0.6852],
        [-1.4233,  0.0232,  0.8065,  1.3902],
        [ 0.4132,  1.2145, -1.3166,  1.1124],
        [-1.1225, -0.9744,  1.3258,  0.0935]])

C
 tensor([[-1.2887, -0.3150,  0.9162,  0.8748],
        [-1.0553, -0.1723, -1.0406, -1.0359]])


In [50]:
# can use same @ sign notation as in numpy section
print("A x B")
print(np.round(tensorA@tensorB, 2))

A x B
tensor([[ 1.2000,  2.1800, -2.3200, -0.6100],
        [-5.3300, -0.0100,  3.0400,  1.7900]])


In [52]:
# can multiple by numpy matrix, but will need to convert it to a tensor
# python can do this automatically in the background, but I'm doing it explicitly for practice
matrixD = np.random.randn(4,5)
tensorD = torch.tensor(matrixD, dtype=torch.float) # converting numpy matrix to pytorch tensor
print("tensorC x tensorD")
print(np.round(tensorC@tensorD, 2))

tensorC x tensorD
tensor([[-3.0500,  0.5300,  4.2800, -1.7900, -4.6800],
        [-2.3500,  2.1800, -1.3000,  2.1900,  0.7700]])


# Key take away: Inner dimensions must match to be able to multiple matrices
( M1 X *N1* ) ( *M2* X N2 )<br>
**N1 must equal M2**<br>
Product matrix will be dimension ( M1 X N2 )<br>
***
EX: <br>
Matrix A: 5x**3**<br>
Matrix B: **3**x6<br>
(5x**3**)(**3**x6)<br>
3 == 3<br>
Product dimension: 5x6<br>