In [2]:
# import needed libraries
import numpy as np
import torch

# Using numpy for transposing

In [8]:
# creating a vector
newV = np.array([[4,3,2,1]])
print(newV, "\n")

# transposing the vector
print(newV.T, "\n")

# transpose the transpose
newVectorT = newV.T
print(newVectorT.T)

[[4 3 2 1]] 

[[4]
 [3]
 [2]
 [1]] 

[[4 3 2 1]]


In [10]:
# create the matrix
newM = np.array([[4,3,2,1],
                 [8,7,6,5]])
print(newM, "\n")

# transpose the matrix
print(newM.T, "\n")

# transposing the transpose
newMatrixT = newM.T
print(newMatrixT.T)

[[4 3 2 1]
 [8 7 6 5]] 

[[4 8]
 [3 7]
 [2 6]
 [1 5]] 

[[4 3 2 1]
 [8 7 6 5]]


# Using pytorch for transposing

In [15]:
# create the vector
torchV = torch.tensor([[4,3,2,1]])
print(torchV, "\n")

# transpose the vector 
print(torchV.T, "\n")

# transpose the transpose
torchNewT = torchV.T
print(torchNewT.T)

tensor([[4, 3, 2, 1]]) 

tensor([[4],
        [3],
        [2],
        [1]]) 

tensor([[4, 3, 2, 1]])


In [16]:
# create the matrix
torchM = torch.tensor([[4,3,2,1],
                       [8,7,6,5]])
print(torchM, "\n")

# transpose the matrix 
print(torchM.T, "\n")

# transpose the transpose
torchNewT = torchM.T
print(torchNewT.T)

tensor([[4, 3, 2, 1],
        [8, 7, 6, 5]]) 

tensor([[4, 8],
        [3, 7],
        [2, 6],
        [1, 5]]) 

tensor([[4, 3, 2, 1],
        [8, 7, 6, 5]])
